/**
 * OWNER: Person 3 (Royce/OpenClaw)
 * PURPOSE: GitHub push helper for NightShift continuation agent
 * DEPENDENCIES: GitHub API, src/lib/github.ts
 * STATUS: LIVE — pushes code to GitHub via PRs
 */

import {
  loadGitHubConfig,
  createBranch,
  commitFile,
  createPR,
  branchExists,
} from '../src/lib/github.ts';

/**
 * Push code to GitHub as a pull request
 * 
 * @param {Object} options
 * @param {string} options.userId - Internal user ID
 * @param {string} options.projectName - Project name for branch naming
 * @param {string} options.filePath - Path where file should be committed (e.g., 'src/components/NewFeature.tsx')
 * @param {string} options.content - File content to commit
 * @param {string} options.commitMessage - Commit message
 * @param {string} options.prTitle - Pull request title
 * @param {string} options.prBody - Pull request body
 * @param {boolean} options.dryRun - If true, don't actually push anything
 * @returns {Promise<Object>} - { success, branchName, prUrl, dryRun }
 */
export async function pushToGitHub(options) {
  const {
    userId,
    projectName,
    filePath,
    content,
    commitMessage,
    prTitle,
    prBody,
    dryRun = false,
  } = options;

  // Load GitHub config
  const config = loadGitHubConfig(userId);
  
  if (!config || !config.token) {
    throw new Error('GitHub not connected for this user');
  }

  if (!config.defaultRepo) {
    throw new Error('No default repository configured');
  }

  const { token, defaultOwner, defaultRepo, defaultBranch } = config;

  // Generate branch name: nightshift/{project-name}-{date}
  const date = new Date().toISOString().split('T')[0];
  const safeName = projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40);
  const branchName = `nightshift/${safeName}-${date}`;

  if (dryRun) {
    return {
      success: true,
      dryRun: true,
      plan: {
        repository: `${defaultOwner}/${defaultRepo}`,
        baseBranch: defaultBranch,
        newBranch: branchName,
        filePath,
        commitMessage,
        prTitle,
        prBody,
        contentPreview: content.slice(0, 200) + (content.length > 200 ? '...' : ''),
      },
    };
  }

  try {
    // Check if branch already exists
    const exists = await branchExists(token, defaultOwner, defaultRepo, branchName);
    
    if (exists) {
      // Branch exists, use it (allows multiple commits to same PR)
      console.log(`Branch ${branchName} already exists, will commit to it`);
    } else {
      // Create new branch
      console.log(`Creating branch: ${branchName}`);
      await createBranch(token, defaultOwner, defaultRepo, defaultBranch, branchName);
    }

    // Commit file
    console.log(`Committing file: ${filePath}`);
    await commitFile(
      token,
      defaultOwner,
      defaultRepo,
      branchName,
      filePath,
      content,
      commitMessage
    );

    // Create pull request (only if branch is new)
    let prUrl = null;
    if (!exists) {
      console.log('Creating pull request...');
      const pr = await createPR(
        token,
        defaultOwner,
        defaultRepo,
        prTitle,
        prBody,
        branchName,
        defaultBranch
      );
      prUrl = pr.html_url;
    } else {
      // If branch exists, PR should already exist
      prUrl = `https://github.com/${defaultOwner}/${defaultRepo}/pulls`;
    }

    return {
      success: true,
      branchName,
      prUrl,
      repository: `${defaultOwner}/${defaultRepo}`,
    };
  } catch (error) {
    console.error('GitHub push error:', error);
    throw error;
  }
}

/**
 * Generate PR body for a code continuation
 */
export function generatePRBody(projectName, projectDescription, nextStep, tokensUsed) {
  return `## 🌙 NightShift AI: Continued Work

**Project:** ${projectName}

${projectDescription ? `**Description:** ${projectDescription}\n\n` : ''}**Next Step:** ${nextStep}

---

### What was generated

NightShift analyzed your conversation history and project context to continue this work while you were away. This code was generated autonomously based on:

- Previous conversation context
- Project requirements and patterns
- Best practices for the detected tech stack

### Review checklist

- [ ] Code follows project conventions
- [ ] No sensitive data or credentials included
- [ ] Tests are included (if applicable)
- [ ] Documentation is updated (if applicable)

### Generated by

🤖 NightShift AI Continuation Agent  
📊 Tokens used: ${tokensUsed}  
⏰ Generated: ${new Date().toISOString()}

---

*This PR was created automatically by NightShift. Review carefully before merging.*
`;
}
